name-template: 'v$NEXT_PATCH_VERSION 🌈'
tag-template: 'v$NEXT_PATCH_VERSION'
prerelease: true
categories:
  - title: 🚀 New Features and Improvements
    labels:
      - feature
      - enhancement
  - title: 🐛 Bug Fixes
    labels:
      - fix
      - bugfix
      - bug
  - title: 📝 Documentation updates
    label: documentation
  # Default label used by Dependabot
  - title: 📦 Dependency updates
    label: dependencies
  - title: 👻 Maintenance
    labels:
      - chore
      - internal
  - title: 🚦 Tests
    labels:
      - test
      - tests
exclude-labels:
  - reverted
  - no-changelog
  - skip-changelog
  - invalid
#change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  <!-- Optional: add a release summary here -->

  # Changes
  $CHANGES

  # Contributors
  Thanks to all the contributors of this release: $CONTRIBUTORS

replacers:
  - search: '@dependabot-preview'
    replace: '@dependabot'