name: List installed browsers

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    paths:
      - '.github/workflows/list-installed-browsers-of-gh-action-runners.yml'

jobs:
  windows_browsers:
    runs-on: windows-2019
    steps:
      - name: Ping
        run: echo "I am alive"
      - name: Check Edge with WmiObject
        shell: powershell
        run: Get-WmiObject -Class Win32_Product | where Name -Like "*Edge*"
      - name: Check Edge with AppxPackage
        shell: powershell
        run: Get-AppxPackage -Name "Microsoft.MicrosoftEdge.Stable"
      - name: Check Chrome with WmiObject
        shell: powershell
        run: Get-WmiObject -Class Win32_Product | where Name -Like "*Chrome*"


  ubuntu_browsers:
    runs-on: ubuntu-20.04
    steps:
      - name: Check Chrome
        run: apt show google-chrome-stable
